nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    HMC_ADMIN_UI_BASE_URL: https://${SERVICE_FQDN}
idam-pr:
  enabled: true
  redirect_uris:
    hmc_admin_ui:
      - https://${SERVICE_FQDN}/oauth2/callback
